[package]
name = "xi-win-ui"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Raph Levien <raph@google.com>"]
description = "Simple Entity Component System UI toolkit layer."

[dependencies]
directwrite = "0.1.2"
direct2d = "0.1.1"

[dependencies.xi-win-shell]
path = "../xi-win-shell"
