[package]
name = "xi-win"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Raph Levien <raph@google.com>"]
description = "Windows front-end for xi editor."

[dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
user32-sys = "0.1"
ole32-sys = "0.2"
uuid-sys = "0.1"
directwrite = "0.0.6"
direct2d = "0.0.6"

#winapi = { git = "https://github.com/retep998/winapi-rs", branch = "0.2" }
#user32-sys = { git = "https://github.com/retep998/winapi-rs", branch = "0.2" }
#gdi32-sys = { git = "https://github.com/retep998/winapi-rs", branch = "0.2" }
#uuid-sys = { git = "https://github.com/retep998/winapi-rs", branch = "0.2" }
#ole32-sys = { git = "https://github.com/retep998/winapi-rs", branch = "0.2" }

gdi32-sys = "0.2"

xi-core-lib = "0.2"
xi-rpc = "0.2"
serde = "1.0"
serde_json = "1.0"

[build-dependencies]
winapi-build = "0.1.1"
