[package]
name = "wintoy2"
version = "0.1.0"
authors = ["Raph Levien <raph@google.com>"]

[dependencies]
winapi = "0.2"
uuid = "0.1"
kernel32-sys = "0.2"
user32-sys = "0.1"
directwrite = "0.0.5"
direct2d = "0.0.5"

#winapi = { git = "https://github.com/retep998/winapi-rs", branch = "0.2" }
#user32-sys = { git = "https://github.com/retep998/winapi-rs", branch = "0.2" }
#gdi32-sys = { git = "https://github.com/retep998/winapi-rs", branch = "0.2" }
#uuid-sys = { git = "https://github.com/retep998/winapi-rs", branch = "0.2" }
#ole32-sys = { git = "https://github.com/retep998/winapi-rs", branch = "0.2" }

gdi32-sys = "0.2"
